apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
stringData:
  DB_USER: postgres
  DB_PASSWORD: postgresql
  USER_RABBIT: guest
  PASSWORD_RABBIT: guest
  SECRET_KEY: C6slIxtVM5y1mBrCphrqygYNVoN7t5V/03NVfJddayQ=
