apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nexus

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml

commonLabels:
  app: nexus
  app.kubernetes.io/name: nexus-multithread
  app.kubernetes.io/part-of: nexus
